import type { Metadata } from "next";

import { LegalPage, type LegalBlock } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms governing your access to and use of CivicScribe, operated by ATP Consulting LLC.",
};

const UPDATED = "June 18, 2026";

const BLOCKS: LegalBlock[] = [
  {
    kind: "p",
    text: `These Terms of Service ("Terms") govern your access to and use of CivicScribe (the "Service"), operated by ATP Consulting LLC ("ATP Consulting," "we," "us," or "our"). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.`,
  },

  { kind: "h2", text: "The Service" },
  {
    kind: "p",
    text: `CivicScribe captures, transcribes, and summarizes meetings — primarily open meetings of public bodies — and can publish the results to a public, searchable library. Transcripts and summaries are produced by automated systems.`,
  },

  { kind: "h2", text: "Eligibility and accounts" },
  {
    kind: "p",
    text: `You must be capable of forming a binding contract to use the Service. Staff and administrator accounts are issued at our discretion. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account, and you agree to notify us promptly of any unauthorized use.`,
  },

  { kind: "h2", text: "Recording authorization and your representations" },
  {
    kind: "p",
    text: `You are solely responsible for ensuring that any meeting you submit may lawfully be recorded, transcribed, and, if you request, published. By submitting a meeting, you represent and warrant that:`,
  },
  {
    kind: "ul",
    items: [
      `the meeting is an open meeting of a public body that the public is entitled to record, or you otherwise have the authority and all consents required to record, transcribe, and publish it;`,
      `your submission and its publication comply with all applicable laws, including recording, wiretap, eavesdropping, two-party-consent, and open-meeting laws in every applicable jurisdiction;`,
      `you will provide any notice to, and obtain any consent from, participants that the law requires; and`,
      `your submission does not infringe the rights of, or violate any obligation owed to, any third party.`,
    ],
  },
  {
    kind: "callout",
    text: `You bear full responsibility for the lawful basis to record and publish any meeting you submit. Do not use the Service to record private, confidential, or non-public meetings without proper authority and consent.`,
  },

  { kind: "h2", text: "Acceptable use" },
  { kind: "p", text: `You agree not to:` },
  {
    kind: "ul",
    items: [
      `use the Service to record or publish any meeting unlawfully or without the rights described above;`,
      `submit content that is unlawful, defamatory, harassing, or that infringes the rights of others;`,
      `attempt to gain unauthorized access to the Service, its data, or its infrastructure;`,
      `interfere with or disrupt the integrity or performance of the Service; or`,
      `use the Service to harass, intimidate, threaten, or coerce any person.`,
    ],
  },

  { kind: "h2", text: "AI-generated content; no official record" },
  {
    kind: "p",
    text: `Transcripts, summaries, topics, and related output are generated by automated systems and may contain inaccuracies, omissions, or errors. They are provided for convenience and accessibility only, are not legal advice, and are not an official record of any meeting. You should not rely on them as a substitute for the official minutes or recording maintained by the relevant public body.`,
  },

  { kind: "h2", text: "Publication and removal" },
  {
    kind: "p",
    text: `Publishing a meeting makes its content publicly accessible and searchable. We may, at our discretion and without notice, decline to publish, remove, or modify any content, including to comply with law, respond to a credible request, or protect the Service or third parties. We are not obligated to retain or continue to host any content.`,
  },

  { kind: "h2", text: "Intellectual property" },
  {
    kind: "p",
    text: `The Service, including its software, design, and branding, is owned by ATP Consulting and protected by intellectual-property laws. Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable right to use the Service. Underlying meeting content remains subject to the rights of its sources and the public-record status of the proceedings it documents.`,
  },

  { kind: "h2", text: "Disclaimer of warranties" },
  {
    kind: "callout",
    text: `THE SERVICE AND ALL CONTENT ARE PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT.`,
  },
  {
    kind: "p",
    text: `We do not warrant that the Service will be uninterrupted, secure, or error-free, or that any transcript or summary will be accurate or complete.`,
  },

  { kind: "h2", text: "Limitation of liability" },
  {
    kind: "callout",
    text: `TO THE FULLEST EXTENT PERMITTED BY LAW, ATP CONSULTING LLC AND ITS MEMBERS, MANAGERS, AND AGENTS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICE.`,
  },
  {
    kind: "p",
    text: `Our total liability for any claim arising out of or relating to the Service will not exceed the greater of the amount you paid us to use the Service in the twelve months preceding the claim, or one hundred U.S. dollars (US$100).`,
  },

  { kind: "h2", text: "Indemnification" },
  {
    kind: "callout",
    text: `You agree to indemnify, defend, and hold harmless ATP Consulting LLC and its members, managers, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising out of or related to: (a) any meeting you submit; (b) your breach of these Terms; (c) your misrepresentation of your authority or lawful basis to record or publish; or (d) your violation of any law or the rights of any third party.`,
  },

  { kind: "h2", text: "Third-party services" },
  {
    kind: "p",
    text: `The Service relies on third-party providers (including Recall.ai, AssemblyAI, Anthropic, Supabase, Railway, and Resend) and may interoperate with third-party meeting platforms. We are not responsible for the acts, omissions, or terms of those third parties, and your use of any meeting platform remains subject to that platform's own terms.`,
  },

  { kind: "h2", text: "Termination" },
  {
    kind: "p",
    text: `We may suspend or terminate your access to the Service at any time, with or without notice, including for any violation of these Terms. Provisions that by their nature should survive termination — including ownership, disclaimers, limitation of liability, and indemnification — will survive.`,
  },

  { kind: "h2", text: "Governing law and disputes" },
  {
    kind: "p",
    text: `These Terms are governed by the laws of the State of New Hampshire, without regard to its conflict-of-laws rules. Any dispute arising out of or relating to the Service or these Terms will be brought exclusively in the state or federal courts located in New Hampshire, and you consent to the personal jurisdiction of those courts. This choice of law governs the agreement between you and ATP Consulting; it does not change the recording, open-meeting, or other laws that apply to a given meeting based on where it takes place.`,
  },

  { kind: "h2", text: "Changes to these Terms" },
  {
    kind: "p",
    text: `We may revise these Terms from time to time. Material changes will be reflected by updating the "Last updated" date above. Your continued use of the Service after changes take effect constitutes acceptance of the revised Terms.`,
  },

  { kind: "h2", text: "Miscellaneous" },
  {
    kind: "p",
    text: `If any provision of these Terms is held unenforceable, the remaining provisions will remain in full force. Our failure to enforce any provision is not a waiver of it. These Terms constitute the entire agreement between you and ATP Consulting regarding the Service and supersede any prior agreements on that subject.`,
  },

  { kind: "h2", text: "Contact us" },
  {
    kind: "contact",
    intro: `Questions about these Terms can be sent to ATP Consulting LLC at`,
    email: "admin@atpconsultancy.com",
  },
];

export default function TermsPage() {
  return <LegalPage title="Terms of Service" updated={UPDATED} blocks={BLOCKS} />;
}
