import type { Metadata } from "next";

import { LegalPage, type LegalBlock } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How ATP Consulting LLC collects, uses, and protects information in connection with CivicScribe.",
};

const UPDATED = "June 18, 2026";

const BLOCKS: LegalBlock[] = [
  {
    kind: "p",
    text: `This Privacy Policy describes how ATP Consulting LLC ("ATP Consulting," "we," "us," or "our") collects, uses, shares, and protects information in connection with CivicScribe (the "Service"), a tool that captures, transcribes, and summarizes public meetings to make civic proceedings accessible and searchable.`,
  },
  {
    kind: "p",
    text: `By accessing or using the Service, you acknowledge that you have read and understood this Privacy Policy. If you do not agree with it, do not use the Service.`,
  },

  { kind: "h2", text: "Who we are" },
  {
    kind: "p",
    text: `CivicScribe is operated by ATP Consulting LLC, a New Hampshire limited liability company. ATP Consulting is the controller responsible for the information processed through the Service. You can reach us using the contact details at the end of this policy.`,
  },

  { kind: "h2", text: "Information we collect" },
  { kind: "p", text: `We collect the following categories of information:` },
  { kind: "h3", text: "Meeting content" },
  {
    kind: "p",
    text: `Audio recordings of meetings captured through the Service, transcripts generated from that audio, speaker labels and any speaker names applied, and AI-generated summaries. This content may include the voices, names, and statements of meeting participants and members of the public who speak during a meeting.`,
  },
  { kind: "h3", text: "Account information" },
  {
    kind: "p",
    text: `If you hold a staff or administrator account, we store your email address, a securely hashed password, your assigned role, and the basic account activity needed to operate the Service.`,
  },
  { kind: "h3", text: "Submission details" },
  {
    kind: "p",
    text: `When a meeting is submitted, we collect the meeting URL or source, the name of the public body, your attestation of the lawful basis for recording (for example, that it is an open meeting of a public body, or that you are otherwise authorized), any request to publish the meeting, and, if you provide one, an email address for completion notifications.`,
  },
  { kind: "h3", text: "Technical and usage data" },
  {
    kind: "p",
    text: `We collect limited technical data, including IP addresses (used for rate limiting and abuse prevention), session cookies used to keep signed-in staff authenticated, and single-meeting view tokens that grant temporary private access to a result.`,
  },

  { kind: "h2", text: "How we use information" },
  {
    kind: "ul",
    items: [
      `Provide, operate, maintain, and improve the Service.`,
      `Capture, transcribe, summarize, and publish meeting content as directed.`,
      `Authenticate staff accounts and secure the Service.`,
      `Prevent abuse, enforce usage limits, and protect the integrity of the Service.`,
      `Respond to your requests and communicate with you about the Service.`,
      `Comply with legal obligations and enforce our Terms of Service.`,
    ],
  },

  { kind: "h2", text: "Publication and the public record" },
  {
    kind: "p",
    text: `When a meeting is published to the public library, its transcript, summary, topics, and associated audio become publicly accessible and searchable. Published content is intended to be a lasting public record and may be cached, indexed by search engines, or copied by third parties. Removing content from the Service may not remove copies that others have already made.`,
  },
  {
    kind: "callout",
    text: `Transcripts and summaries are generated by automated systems and may contain errors. They are not an official record of any meeting.`,
  },

  { kind: "h2", text: "How meetings are recorded" },
  {
    kind: "p",
    text: `Meetings are recorded with notice. When the recording assistant joins a meeting, it identifies itself in the participant list and posts a notice that the meeting is being recorded for live captions and a transcript. For open meetings of public bodies in Massachusetts, recording is permitted under the Massachusetts Open Meeting Law, G.L. c. 30A, § 20. Responsibility for the lawful basis to record any given meeting rests with the person who submits it, as described in our Terms of Service.`,
  },

  { kind: "h2", text: "Service providers and international processing" },
  {
    kind: "p",
    text: `We share information with third-party service providers that process it on our behalf, only as needed to operate the Service:`,
  },
  {
    kind: "ul",
    items: [
      `Recall.ai — provides the meeting-recording assistant that joins and captures meetings.`,
      `AssemblyAI — transcribes meeting audio and identifies speakers.`,
      `Anthropic — generates meeting summaries from transcripts.`,
      `Supabase — database and storage for meeting data and audio.`,
      `Railway — application hosting and infrastructure.`,
      `Resend — delivery of transactional email, when email notifications are enabled.`,
    ],
  },
  {
    kind: "p",
    text: `These providers may process data in the United States. We do not sell personal information, and we do not share it for cross-context behavioral advertising.`,
  },

  { kind: "h2", text: "Data retention" },
  {
    kind: "p",
    text: `We retain meeting content for as long as it remains in the Service or until it is deleted by staff or by request. Account information is retained for the life of the account. Technical data, such as IP-based rate-limit records, is retained only as long as needed for security and abuse prevention. Published content may persist as part of the public record until removed.`,
  },

  { kind: "h2", text: "Security" },
  {
    kind: "p",
    text: `We use reasonable administrative and technical safeguards to protect information, including encryption in transit, hashed passwords, scoped service credentials, and access controls. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.`,
  },

  { kind: "h2", text: "Your rights and choices" },
  {
    kind: "p",
    text: `Depending on your location, you may have rights to access, correct, or delete personal information about you, or to object to or restrict certain processing. To exercise these rights, contact us using the details below, and we will respond consistent with applicable law. For content that forms part of the public record of a government proceeding, our ability to alter or remove it may be limited.`,
  },
  { kind: "h3", text: "Removing or correcting published content" },
  {
    kind: "p",
    text: `If you are identified in a published meeting and wish to request correction or removal — for example, a member of the public who spoke during public comment — contact us with enough detail to locate the content. We review each request and act where appropriate, balancing individual interests against the public interest in an accurate civic record.`,
  },

  { kind: "h2", text: "Cookies" },
  {
    kind: "p",
    text: `The Service uses a small number of strictly necessary cookies, primarily to keep signed-in staff authenticated. We do not use advertising or third-party tracking cookies.`,
  },

  { kind: "h2", text: "Children's privacy" },
  {
    kind: "p",
    text: `The Service is not directed to children under 13, and we do not knowingly collect personal information from children. Members of the public, including minors, may nonetheless appear in recordings of public meetings; requests concerning such content can be made using the contact details below.`,
  },

  { kind: "h2", text: "Changes to this policy" },
  {
    kind: "p",
    text: `We may update this Privacy Policy from time to time. Material changes will be reflected by updating the "Last updated" date above. Your continued use of the Service after changes take effect constitutes acceptance of the revised policy.`,
  },

  { kind: "h2", text: "Contact us" },
  {
    kind: "contact",
    intro: `Questions or requests regarding this Privacy Policy can be sent to ATP Consulting LLC at`,
    email: "admin@atpconsultancy.com",
  },
];

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" updated={UPDATED} blocks={BLOCKS} />;
}
